### ISSUE TITLE
Koishi Online Roadmap

### ISSUE THREAD

**Issue by shigma** [koishijs/webui#31]
[Koishi Online](https://koishi.online) 是一个无后端的在线 Koishi 应用。一方面，新用户得以尽情体验 Koishi 的各项特性，无需安装任何环境；另一方面，插件开发者也获得了一种更加直观的展现插件功能的途径。

## 开发计划

Koishi Play 的开发计划分为两个阶段：

- 第一阶段：技术验证
  - [x] 实现 Koishi 及其核心插件的前端运行
  - [x] 构建预生成的插件市场 ([@koishijs/registry](https://github.com/koishijs/registry))
  - [x] 实现虚拟配置文件的读写 ([@koishijs/loader](https://github.com/koishijs/koishi/blob/master/packages/loader))
  - [x] 实现多实例切换，支持从请求创建实例

- 第二阶段：更多兼容性
  - [x] 实现数据库插件的前端运行
  - [x] 实现适配器插件的前端运行
  - [x] 实现渲染功能的前端运行
